### ISSUE TITLE
Can't reuse COM Library from the calling thread when using in Electron's main process

### ISSUE THREAD

**Issue by 6ixfalls** [xan105/node-processMonitor#5] opened 2021-08-01 22:39 UTC
I've recently found this module through extensive google searching, and it fits exactly what I need. However, it fails to start properly, and when WQL.subscribe or WQL.promises.subscribe is called, the process instantly quits. I've backtracked the issue to createEventSink, and when it's called, the process suddenly quits.

Here's how I use this module:

```js
const processMonitor = WQL.subscribe({
    filterWindowsNoise: true
});

processMonitor.on("creation", async ([process, pid, filepath]) => {
    // code
});

processMonitor.on("deletion", ([process, pid]) => {
    // code
});
```

**Comment by xan105** [comment] 2021-08-02 04:53
Are you using the version on npm (@1.4.0) ?

Because then you need to
1. **Initialize the event sink by using createEventSink().**
2. Subscribe to event(s) of your choosing : creation, deletion, or both by using subscribe({options}).
3. You need to keep node.js event loop alive.

```js
"use strict";

const WQL = require("wql-process-monitor");

(async () => {
  await WQL.promises.createEventSink(); //That's missing in your usage example
  console.log("createEventSink");

  const processMonitor = await WQL.promises.subscribe({ filterWindowsNoise: false });
  console.log("subscribe");

  processMonitor.on("creation", ([process, pid, filepath]) => {
    console.log(`\x1b[32mcreation\x1b[0m: ${process}::${pid} [\x1b[90m${filepath}\x1b[0m]`);
  });

  processMonitor.on("deletion", ([process, pid]) => {
    console.log(`\x1b[31mdeletion\x1b[0m: ${process}::${pid}`);
  });
  
  /*
  Keep alive
  You don't need this if you have something else to keep the event loop running.
  This is just as an example so node.js doesn't exit directly.
  */
  setInterval(() => {}, 1000 * 60 * 60);
})().catch(console.error);
```

![example](https://user-images.githubusercontent.com/14090532/127805622-287f2e41-8749-46b7-a328-a71ccc3b2cfd.png)

**Comment by 6ixfalls** [comment] 2021-08-02 07:31
I've tried using both the npm and github versions, both produce the same output. I listen to the events right after i call subscribe, and even then, nodejs just exits. I'm running this on electron, and the process stays alive when I dont call createEventSink/subscribe.

I've also tried just adding the setInterval like shown but it didnt work either.

**Comment by xan105** [comment] 2021-08-02 10:36
Sorry for answer delay, I never _personally_ tested it under electron before, so I had to make sure.

_Electron 13 x64 (node 14)_
![electron](https://user-images.githubusercontent.com/14090532/127846430-8d3af13e-0000-4da8-97b6-f1d8fe25896a.png)

You don't have any crash log or anything ? I'm in the blind here so on the top of my head :

- Pretty sure you need to have VC redist 2015-2019 installed (for the .dll of my lib)
- You have to recompile node-ffi-napi with electron's header. I usually use the package `electron-rebuild` for that.
I like to add `"native-rebuild": "call .\\node_modules\\.bin\\electron-rebuild.cmd"` in `package.json` under `scripts`.
And call it with `npm run-script native-rebuild`.
But depending on your workflow and whatever tools you are using they are alternatives that do the same.
- In the `webPreferences` of your window, make sure that `nodeIntegration` is set to `true` (I'm also using `contextIsolation` to `false`; don't know if that's needed)
- If you are using the npm version you need to call `createEventSink()` at least once before `subscribe()` or it will fail.

edit: You don't need the setInterval() in electron

**Comment by 6ixfalls** [comment] 2021-08-02 15:21
I've tried the methods you've listed above, however, it still doesn't work.
I've already installed VC redistributable 2015-2019, and I've tried using electron-rebuild. Both didn't change anything and the process still suddenly ends.
I'm doing the code entirely in the main electron script since I'm only using electron for the contextMenu.

I'm confused as to why it suddenly stops, as there are no logs, etc that occur after createEventSink is called. It just stops the process without any logging.

**Comment by xan105** [comment] 2021-08-03 06:12
My test was in the renderer process ~but it works just the same in the main process~ (edit: see below).
I made some changes to how the error is sent back. Process shouldn't crash and the error is sent as a response code.
Give it a try (_github version_) ?

**Comment by 6ixfalls** [comment] 2021-08-03 15:04
Yeah, that made it log an error. Here's the error:

```
(node:3836) UnhandledPromiseRejectionWarning: Failure: ERR_EVENTSINK_INIT_FAIL: Failed to initialize COM library
    at Object.createEventSink (C:\Users\brypo\Downloads\rblxRP-2.3.0\node_modules\wql-process-monitor\lib\processMonitor.cjs:153:26)
    at Object.subscribe (C:\Users\brypo\Downloads\rblxRP-2.3.0\node_modules\wql-process-monitor\lib\processMonitor.cjs:168:10)
    at BeginListener (C:\Users\brypo\Downloads\rblxRP-2.3.0\richPresence.js:39:32)
    at RPCClient.<anonymous> (C:\Users\brypo\Downloads\rblxRP-2.3.0\index.js:114:5)
    at RPCClient.emit (events.js:315:20)
    at RPCClient.login (C:\Users\brypo\Downloads\rblxRP-2.3.0\node_modules\discord-rpc\src\client.js:146:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

If it helps, I'm on Windows 19043.1110.

**Comment by xan105** [comment] 2021-08-03 21:05
Ok, so after a very long time reading docs, trying stuff, etc and etc ... I think I figured out the root of the problem.
Finally **it is** because you are using my lib in the main process.

Reason is electron initializes a COM interface (_after the ready event_) for its own thread which will get use by my lib through node-ffi-napi.
Init. the COM interface over an already init. one is _fine_ as long as it uses the same thread model.
And depending on what you do with the COM it might even work with different thread model.

The problem is that electron sets is thread model to something else than `COINIT_MULTITHREADED` which after testing is required for what I'm doing or it just breaks.
Because of the way node-ffi-napi spawns other threads via libuv when using `.async()` (_WQL.promises in short_) you might get pass this. But they are still some failing points afterwards notably when setting up security for the process->COM interface.

This is going very low level for me and my very basic knowledge of C++. 
Ideally because my COM interface is in a .dll Micrososft advises that 
- I run it in a separate thread of its own inside the dll 
- and to absolutely not init. the COM interface in the dllMain (I don't already). 
But I honestly have no clues how to make and convert it to a C++ multi threaded .dll and interface it with node-ffi-napi.

NB: If I said previously that it worked for me in the main process it's because, don't ask me why, but running my example [anonymous self executed async function with WQL.promises methods](https://github.com/xan105/node-processMonitor/blob/main/test/test_async.cjs) outside of `app.on('ready', ()=>{})` was fine.

NB2: There is a very ugly hack to just call `CoUninitialize()` before calling `CoInitializeEx()` to kinda _"force it"_ but that could cause unexpected issues to the caller COM interface (here Electron) so I'm not gonna do that either 😅

**Comment by xan105** [comment] 2021-08-04 07:24
I've tried a bunch of things regarding multi-thread alas without any success. I'm giving up sorry. 
This will stay as it is as it's _fine_ 99% of the time (as I mentioned earlier).
_Edit: plus node-ffi-napi recommend to avoid any multi-threading usage_

I haven't tested these but there are 2 approaches for running non-blocking background tasks  (_separate process_) in Electron 
that ~could~ should workaround the issue :
- Using web workers
- Using a hidden browser window and communicate between the main process and background window via electron's IPC.

**Comment by 6ixfalls** [comment] 2021-08-04 17:09
Thanks for the help! I was able to get it working by spawning a child process to execute this module for me.

**Comment by xan105** [comment] 2021-08-04 18:02
Glad you were able to find an elegant solution (didn't think of forking child process and such 😅)
I'm closing this then 😉

**Closed as completed by xan105** 2021-08-04 18:02 UTC
Labels: help wanted, wontfix
